# NOT FOR PROD
services:
  back:
    image: golang:1.23-alpine
    volumes:
      - ./backend:/usr/src/server
    working_dir: /usr/src/server
    expose:
      - 8080
    ports:
      - ${BACK_PORT}:8080
    command: sh -c "go build -o ./build/server server.go && ./build/server"

  vue:
    image: node:22-alpine
    volumes:
      - ./vue:/usr/src
    working_dir: /usr/src
    ports:
      - ${VUE_PORT}:5173
    command: sh -c "npm run dev -- --host vue"

  angular-rxjs:
    image: node:24.15-alpine
    volumes:
      - ./angular-rxjs:/usr/src
    working_dir: /usr/src
    ports:
      - ${ANGULAR_RXJS_PORT}:4200
    command: sh -c "npm start"

  angular-signal:
    image: node:24.15-alpine
    volumes:
      - ./angular-signal:/usr/src
    working_dir: /usr/src
    ports:
      - ${ANGULAR_SIGNAL_PORT}:4200
    command: sh -c "npm start"

  next:
    image: node:24.15-alpine
    volumes:
      - ./next:/usr/src
    working_dir: /usr/src
    environment:
      BACK_URL: http://back:8080
    ports:
      - ${NEXT_PORT}:3000
    command: sh -c "npm run dev"
